apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-vik-deployment
  labels:
    app: app1-vik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-vik
  template:
    metadata:
      labels:
        app: app1-vik
    spec:
      containers:
        - name: app1-vik
          image: aksdevopsacr.azurecr.io/custom2aksnginxapp1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-vik-loadbalancer-service
  labels:
    app: app1-vik
spec:
  type: LoadBalancer
  selector:
    app: app1-vik
  ports:
    - port: 80
      targetPort: 80
